name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: TicTacToe
          POSTGRES_DB: TicTacToeDb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    - name: Restore dependencies
      run: dotnet restore TicTacToe.Api/TicTacToe.Api.sln

    - name: Build
      run: dotnet build TicTacToe.Api/TicTacToe.Api.sln --no-restore

    - name: Run tests
      run: dotnet test TicTacToe.Api/TicTacToe.Api.sln --no-build --verbosity normal
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Database=TicTacToeDb;Username=postgres;Password=TicTacToe"